Updating rails from 5.2.3 to 6.1.2
3scale/zync pull request #440
Opened 2021-03-08 06:34 UTC by HemaHG

Updating rails from 5.2.3 to 6.1.2

2021-03-31 10:42 UTC, hallelujah requested changes

2021-03-31 10:58 UTC, HemaHG commented on Gemfile
> +gem 'ransack', github: 'activerecord-hackery/ransack'
this is outdated, I have updated the Gemfile, not using ransack

2021-03-31 15:18 UTC, hallelujah requested changes
This is a regression

And if it is not tested then it should

https://github.com/3scale/zync/commit/3d6ab1e37b51537a55d94fb57786550663d7cc20#r48945764

2021-04-12 10:02 UTC, hallelujah approved these changes
LGTM 🚀

2021-04-22 16:42 UTC, merged